#!/bin/bash
core_dir=/data/storage/corefiles
#core_file_num=`ls -t $core_dir/core* | wc -l`
core_file_num=`ls $core_dir/ | grep core | wc -l`
#echo "initial value:$core_file_num"
while [ 1 -eq 1 ]
do
	sleep 5
	cur_core_file_num=`ls $core_dir/ | grep core | wc -l`
#	echo "current value:$cur_core_file_num"
#	echo "previous value:$core_file_num"
	if [ $core_file_num -ge $cur_core_file_num ]
	then
		core_file_num=$cur_core_file_num
	else 
		diff_num=$(($cur_core_file_num - $core_file_num))
	
#		echo $diff_num
		core_file_num=$cur_core_file_num
		core_array=`ls -t $core_dir/core*`
		for corefile in ${core_array[@]}
		do
			base_corefile=`basename $corefile`
			gdb_str=`gdb --batch -q $corefile 2>/dev/null | grep "Core was generated by"`
			file_para=`ls -all $corefile`
			file_para_array=($file_para)
			echo ${file_para_array[0]}
			wall "=====New Core Dump!!===== filename:$base_corefile; time:${file_para_array[5]} \
${file_para_array[6]} ${file_para_array[7]}; $gdb_str"
            echo -e "\a"
            echo "=====New Core Dump!!===== filename:$base_corefile; time:${file_para_array[5]} \
${file_para_array[6]} ${file_para_array[7]}; $gdb_str" >> record_core.txt
			diff_num=$(($diff_num - 1))
		#	echo $diff_num
			if [ $diff_num -eq 0 ]
			then
				break
			fi
		done
	fi
done
